### ISSUE TITLE
Plugin is not working for me :(

### ISSUE THREAD

**Issue by geekox86** [dhardtke/font-awesome-minify-plugin#9]
Greetings all,

I am trying to get running with this great plugin with no success.

You can find my repo code [here](https://github.com/geekox86/vue-apollo-graphql)

Here is a snippet on how I am configuring the plugin:

```js
    new FontAwesomeMinifyPlugin({
      srcDir: path.resolve(/* path to my source directory */),
    })
```

Here is how I am including the FA css:

```css
@import '@fortawesome/fontawesome-free/css/all';
```

If I run my build script in package.json, I still get full sized font icon files.

What am I doing wrong?

**Comment by dhardtke** [comment]
Hello,

thanks for your issue.

There are multiple things going wrong here:
The plugin is currently looking for CSS files named `fontawesome.css`, `solid.css`, `regular.css`, `brands.css` and `light.css`. Your `globals.css` looks like this:

```css
@import '@fortawesome/fontawesome-free/css/all';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

You will have to change the imports to look like this:
```css
@import '~@fortawesome/fontawesome-free/css/fontawesome.css';
@import '~@fortawesome/fontawesome-free/css/regular.css';
@import '~@fortawesome/fontawesome-free/css/solid.css';
@import '~@fortawesome/fontawesome-free/css/brands.css';
@import '~tailwindcss/dist/components.css';
@import '~tailwindcss/dist/utilities.css';
```

Then, in order for webpack to be able to resolve the tilde (`~`) you will need to adjust the `resolve` configuration:

_webpack/configs/resolve-config.js_:
```js
// rest omitted for brevity
return {
    modules: [
        require('path').resolve(entry.root, 'node_modules')
    ]
}
```

After that, you will notice that the `font-awesome-minify-plugin` still does not do anything. This is because it cannot find any icon classes and bails out.

If you add at least one icon class to your template, the plugin will build new CSS and font files with just that one codepoint included.

I am planning to rewrite this plugin at some point in the future and switch to TypeScript, add unit tests, CI integration, etc. Also, I will try to find a way to process `@fortawesome/fontawesome-free/css/all` as well.

**Comment by geekox86** [comment]
Hi @dhardtke. Thank you for this awesome plugin.

I applied what you suggested and here is what I got so far:

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '~@fortawesome/fontawesome-free/css/fontawesome.css'
  in [
    /Users/geekox86/Documents/GitHub/vue-apollo-graphql/codes
  ]
    at /Users/geekox86/Documents/GitHub/vue-apollo-graphql/node_modules/postcss-import/lib/resolve-id.js:35:13
    at /Users/geekox86/Documents/Git
```

You can find my updated code on the same repo link.

**Comment by dhardtke** [comment]
I also forgot to mention that you also need to disable postcss as it somehow leads to these resolution errors.

**Comment by geekox86** [comment]
Great thanks!

I just needed to remove postcss-import (not the the whole postcss).

BTW, do not you think the plugin should removes all font icon files if no class has been used from FA?

You can consider my issue resolved :)

**Comment by dhardtke** [comment]
Glad it works for you. At this point though I consider the plugin to be quite unstable. It is working in our production environment rather well, but I do see some parts of the plugin to be fragile (e.g. the CSS construction as it is relying on the ordering of classes in FA's CSS files).

> BTW, do not you think the plugin should removes all font icon files if no class has been used from FA?

That's something to debate about I guess. I'll think about it.
